name: 'Setup Appwrite CLI'
description: 'A GitHub Action to setup Appwrite CLI.'
branding:
  icon: 'terminal'
  color: 'red'
inputs:
  endpoint:
    description: 'Appwrite Endpoint'
    required: true
  project:
    description: 'Project ID'
    required: true
  key:
    description: 'API Key'
    required: true
  locale:
    description: 'Locale'
    required: false
    default: 'en-US'
runs:
  using: 'composite'
  steps:
    - name: Install Appwrite CLI
      shell: bash
      run: curl -sL https://appwrite.io/cli/install.sh | bash
    - name: Setup Appwrite CLI
      shell: bash
      run: |
        appwrite init \
          --locale='${{ inputs.locale }}' \
          --endpoint='${{ inputs.endpoint }}' \
          --project='${{ inputs.project }}' \
          --key='${{ inputs.key }}'
        appwrite version
